config/routes.rb
Cadmin::Engine.routes.draw do
  mount Shrine.upload_endpoint(:cache) => "/upload"
  root to: "dashboard#index"
  
  # custom routes
  get 'profile/index'
  get 'profile/edit'
  get 'profile/show'
  # get 'tags/:tag', to: 'articles#index', as: :tag
  match '/',                  to: "dashboard#index",          via: :get,      as: :dashboard
  match '/agenda',            to: "dashboard#agenda",         via: :get,      as: :agenda
  match '/interviews',        to: "interviews#index",         via: :get,      as: :interviews
  match '/interviews/:id',    to: "interviews#show",          via: :get,      as: :interview
  match '/reset-password',    to: "users#reset_password",     via: [:get,:post],      as: :reset_password
  # match '/users', to: "users#index",  via: :get, as: :users
  # match '/charged', to: "events#charged", via: :get, as: :charged
  # match '/events/:id/charged', to: "events#charged", via: :put, as: :charged
  
  # scafold resources
  resources :article_categories
  resources :discounts
  resources :event_types
  resources :locations
  resources :tags
  resources :tracks
  resources :users
  resources :web_modules
    
  resources :articles do
    resources :comments
  end
  resources :conversations do 
    resources :messages
  end

  resources :email_base_templates do
    resources :email_custom_templates, except: %w[show]
  end

  resources :events do
    resources :interviews  
  end
  
  resources :events do
    get 'booked',  on: :member
    get 'charged', on: :member 
    get 'cancel',  on: :member
  end

  resources :main_services do
    resources :services
  end

  # cart actions
  match 'cart', to: "carts#index",  via: :get, as: :cart
  resources :cart_items, only: %w[create destroy]
  get "/add/:service_id", to: "cart_items#create", as: :add_to_cart
  
  # payment routes
  # stripe webhooks
  resources :webhooks, only: %w[create]
  # stripe checkout
  get   'checkout/create',    to: 'checkout#create'
  post  'checkout/create',    to: 'checkout#create'
  get   'success',            to: 'checkout#success'
  get   'cancel',             to: 'checkout#cancel'
  
  # user authentication routes 
  # # devise_for :cadmin_users, class_name: "Cadmin::User", module: :devise
  # devise_for :users, controllers: { invitations: 'devise/invitations' }
  devise_for  :cadmin_users, 
              class_name: "Cadmin::User" , 
              controllers: { 
                sessions: 'cadmin/user_sessions', 
                registrations: 'cadmin/user_registrations',
                invitations: 'cadmin/user_invitations'
              },
              skip: [:sessions, :registrations],
              path_names: {sign_out: 'logout'},
              path_prefix: :user,
              module: :cadmin

  devise_scope :cadmin_user do
    get  'login',        to: 'user_sessions#new',              as: :login
    post 'login',        to: 'user_sessions#create',           as: :create_new_session
    get  'register',     to: 'user_registrations#new',         as: :register
    post 'register',     to: 'user_registrations#create',      as: :registration
    get  'invite',       to: 'user_invitations#new',           as: :invite
    post 'invite',       to: 'user_invitations#create',        as: :invitation
    # get  'profile',      to: 'user_registrations#edit',        as: :edit_profile
    # put  'profile',      to: 'user_registrations#update',      as: :update_profile
    get  'logout',       to: 'user_sessions#destroy',          as: :logout
  end

  # TODO: generate routes for admin and employees
  # namespace :admin do
  #   devise_for :cadmin_user,
  #               class_name: "Cadmin::User",
  #               controllers: {
  #                 sessions: 'cadmin/admin/user_sessions'
  #               },  
  #               skip: [:sessions, :registrations],
  #               path_names: { sign_out: 'logout' },
  #               path_prefix: :user
  #   devise_scope :cadmin_user do
  #     get 'login' => 'user_sessions#new', :as => :login
  #     post 'login' => 'user_sessions#create', :as => :create_new_session
  #   end
  # end

  namespace :api do 
    namespace :v1 do 
      # SPOTIFY API
      resources :tracks do 
        collection do 
          get :top_100
          get :random 
          get :search 
        end 
      end 
    end 
  end
end

app/models/cadmin/application_record.rb
module Cadmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/cadmin/article.rb
module Cadmin
  class Article < ApplicationRecord
    extend FriendlyId

    friendly_id :title, use: :slugged
    
    include PgSearch::Model  
    include ImageUploader::Attachment(:image)
    
    belongs_to :user
    belongs_to :article_category
    
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    serialize :tag_ids, Array

    delegate :username, :name, to: :user
    delegate :name, to: :article_category, prefix: :category
    
    enum status: [:pending, :published, :unpublished, :drafts ]

    validates :title, :content, presence: true

    def self.tagged_with(name)
      Tag.find_by!(name: name).articles
    end

    def self.tag_counts
      Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    end

    def tag_list 
      tags.map(&:name).join(', ')
    end

    def tag_list=(names)
      self.tags = names.split(',').map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
    end

    pg_search_scope :filter_by_search, against: [
      :title, 
      # :content, 
      # todo: complete searches
    ]
    
    def unpublish?
      self.status == 2
    end

    def draft?
      self.status == 3
    end
  end
end

app/models/cadmin/article_category.rb
module Cadmin
  class ArticleCategory < ApplicationRecord
    has_many :articles, dependent: :destroy
    validates :name, presence: true
  end
end

app/models/cadmin/cart.rb
module Cadmin
  class Cart < ApplicationRecord
    include AASM

    has_many :cart_items, dependent: :destroy
    has_many :services, through: :cart_items

    aasm.attribute_name :status

    aasm column: :status do
      state :pending, initial: true
      state :booking

      event :booked do
        transitions from: :pending, to: :booking
      end
    end

    def total_cart_amount
      self.cart_items.sum(&:service_price)
    end

    def deposit_percentage(percentage)
      self.total_cart_amount * percentage / 100
    end
  end
end

app/models/cadmin/cart_item.rb
module Cadmin
  class CartItem < ApplicationRecord
    belongs_to :service
    belongs_to :cart

    delegate :name, :price, :hour_price, :stock, :image_url, :description, :short_dscription, to: :service, prefix: 'service'

    # validates :validate_stock

    def set_cart_data (cart, service_id)
      @cart_ip = cart
      @service_id = service_id
    end

    # TODO: VALIDATION STOCK TO CALCULATE THE QUANTITY OF THE SERVICE IS AVILABLE IN THOSE DAYS
    # def validate_stock
    #   service = Service.find(@service_id)
    #   cart = Cart.find(@cart_ip).cart_items.where(service_id: @service_id)
    #   if service.stock < cart.count
    #     errors.add(:service, "No hay stock suficiente")
    #   end
    # end

  end
end

app/models/cadmin/comment.rb
module Cadmin
  class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :article
    validates :content, presence: true
  end
end

app/models/cadmin/concerns/permission_level.rb
module Cadmin
  module PermissionLevel
    extend ActiveSupport::Concern

    def user?
      %w(user employee admin superadmin).include?(self.role)
    end
    def employee?
      %w(employee admin superadmin).include?(self.role)
    end
    def admin?
      %w(admin superadmin).include?(self.role)
    end
    def superadmin?
      %w(superadmin).include?(self.role)
    end
  end
end

app/models/cadmin/conversation.rb
module Cadmin
  class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, scope: :recipient_id

    scope :between, -> (sender_id, recipient_id) do 
      where("(cadmin_conversations.sender_id = ? AND  cadmin_conversations.recipient_id =?) OR (cadmin_conversations.sender_id = ? AND cadmin_conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
    end
  end
end

app/models/cadmin/discount.rb
module Cadmin
  class Discount < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged
    validates :name, :type_discount, :percentage, :amount, presence: true
  end
end

app/models/cadmin/email_base_template.rb
module Cadmin
  class EmailBaseTemplate < ApplicationRecord
    extend FriendlyId

    friendly_id :title, use: :slugged
    
    has_many :email_custom_templates, dependent: :destroy

    validates :kind, presence: true, uniqueness: true
    validates_presence_of :title, :content

    enum kind: { 
      welcome: 0,
      reset_password: 1,
      new_event_admin: 2,
      new_event_customer: 3,
      confirmation_event: 4,
      customer_update_event: 5,
      employee_update_event: 6,
      billing_is_ready: 7,
      invitation: 8
     }

    def self.pending?
      self.kinds.keys.all? { |kind| self.pluck(:kind).include?(kind) }
    end

    def has_custom_template?
      template = self.email_custom_templates
      template.any? ? template.present? : false
    end
  
    def custom_template
      self.email_custom_templates.first
    end
  end
end

app/models/cadmin/email_custom_template.rb
module Cadmin
  class EmailCustomTemplate < ApplicationRecord
    belongs_to :email_base_template
  
    validates :content, presence: true
  
    delegate :title, :kind, to: :email_base_template, prefix: 'base'
  end
end

app/models/cadmin/event.rb
module Cadmin
  class Event < ApplicationRecord
    include PgSearch::Model
    include Cadmin::DateFormat
    include AASM
    extend FriendlyId

    friendly_id :title, use: :slugged

    belongs_to :customer,                   foreign_key: :customer_id,    class_name: 'User'
    
    belongs_to :employee,   optional: true, foreign_key: :employee_id,    class_name: 'User'
    belongs_to :place,      optional: true, foreign_key: :place_id,       class_name: 'Location'
    
    belongs_to :event_type, optional: true, foreign_key: :event_type_id,  class_name: 'EventType'
    

    has_one :interview, dependent: :destroy
    has_one :cart
    has_many :event_services, dependent: :destroy

    accepts_nested_attributes_for :event_services,
                                  allow_destroy: true,
                                  reject_if: proc { |attr| attr['service_id'].blank? }

    validates :number, presence: true, uniqueness: true  
    validates :title,:event_type, :customer, :place, :event_services, :date, presence: true
    
    # delegate data from users, places and event_types to the view
    delegate :name, :last_name, :avatar, :email, :phone, :address, :birthdate, :city, 
             :province, :postal_code, :shipping_address, :billing_address, 
             to: :customer, prefix: :customer

    delegate :name, :phone, :avatar, to: :employee, prefix: :employee

    delegate :name, to: :event_type, prefix: :type
    delegate :name, to: :place, prefix: :place

    # state machine to change status of event    
    aasm.attribute_name :status
    aasm column: :status do
      state :pending, initial: true
      state :payed, :completed, :cancelled, :booked

      event :book do 
        transitions from: :pending, to: :booked
      end

      event :pay do
        transitions from: [:pending, :booked, :completed], to: :payed
      end

      event :complete do
        transitions from: [:pending, :booked], to: :completed
      end

      event :cancel do
        transitions from: [:pending, :booked], to: :cancelled
      end
    end

    def servicenames 
      self.event_services.map(&:service_name).join(', ')
    end

    def discountnames 
      self.event_services.map(&:disocunts_name).join(',')
    end

    #! create unique number of event
    def create_number
      user = self.customer_id.to_s.rjust(5,"0") 
      number = "LGMD/#{user}-#{ Time.now.strftime('%d%m%y%H%M') }"
      self.number = number 
      self.save
    end

    #! calculate the total of the event for the associated services and discounts
    def total_services_amount
      total = 0
      self.event_services.each do |event_service|
        price = event_service.service_price if event_service.service_price.present?
        discount = event_service.discount_amount if event_service.discount_amount.present?
        discount = (price * event_service.discount_percentage) / 100  if event_service.discount_percentage.present?

        total_hours = event_service.overtime * event_service.service_hour_price

        #! save data on event_service
        event_service.total_amount = price - discount + total_hours
        event_service.save

        #! summation price, discounts and overtime
        total += event_service.total_amount
      end
      total
    end 

    def unallowed_booking? 
      available = []
      self.event_services.each {|es| available << es.in_stock? }
      available.include?(false)
    end

    
    scope :sort_by_date, -> { order('date ASC') }
    # ! SEARCH BETWEEN DATES
    scope :filter_between_dates, ->(start_date, end_date) { where(date: start_date..end_date) }
    scope :filter_by_employee_id, ->(employee_id) { where('employee_id = ?', employee_id) }
    
    # ! pgsearch busqueda por campos de texto
    # pg_search_scope :filter_by_number, against: :number
    pg_search_scope :filter_by_title, against: :title
    pg_search_scope :filter_by_status, against: :status
    
  end
end

app/models/cadmin/event_service.rb
module Cadmin
  class EventService < ApplicationRecord
    belongs_to :event
    belongs_to :service, optional: true
    belongs_to :discount, optional: true

    delegate :name, :price, :hour_price, :stock, :image_url, :description, :short_dscription, to: :service, prefix: 'service'
    delegate :name, :type_discount, :percentage, :amount, to: :discount, prefix: 'discount' 

    def in_stock?
      if StockByDate.find_by(service_id: self.id, date: self.event.date).nil?
        StockByDate.create(
          service_id: self.service_id, 
          date: self.event.date, 
          stock: self.service.stock
        )
      end
      StockByDate.find_by(service_id: self.service_id, date: self.event.date).stock_available?
    end

    def stock_decrement! 
      if StockByDate.find_by(service_id: self.service_id, date: self.event.date).stock_available? 
        sbd = StockByDate.find_by(service_id: self.service_id, date: self.event.date)
        sbd.stock -= 1
        sbd.save!
      end
    end

    def stock_increment! 
      sbd = StockByDate.find_by(service_id: self.service_id, date: self.event.date)
      sbd.stock += 1
      sbd.save!
    end
  end
end

app/models/cadmin/event_type.rb
module Cadmin
  class EventType < ApplicationRecord
    validates :name, presence: true, uniqueness: true 
    validates_presence_of :salary, :overtime_price
  end
end

app/models/cadmin/interview.rb
module Cadmin
  class Interview < ApplicationRecord
    include PgSearch::Model
    include Cadmin::DateFormat
    
    belongs_to :event
    belongs_to :employee, foreign_key: :employee_id, class_name: 'User'
    
    has_many :interview_options, dependent: :destroy    
    accepts_nested_attributes_for :interview_options, allow_destroy: true, reject_if: proc { |attr| attr['gift'].blank? }
    
    delegate :name, :phone, :avatar, to: :employee, prefix: :employee
    delegate :id, :title, :date, :customer_name, :customer_phone, :customer_email, :place_id, to: :event, prefix: :event

    scope :filter_by_pending, -> {Time.now > Event.find(self.event_id).date}
    scope :filter_by_done, -> {Time.now <= Event.find(self.event_id).date}
  end
end

app/models/cadmin/interview_option.rb
module Cadmin
  class InterviewOption < ApplicationRecord
    belongs_to :interview
  end
end

app/models/cadmin/location.rb
module Cadmin
  class Location < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged

    validates :name, presence: true
  end
end

app/models/cadmin/main_service.rb
module Cadmin
  class MainService < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged
    
    has_many :services

    validates :name, presence: true
  end
end

app/models/cadmin/message.rb
module Cadmin
  class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user
    validates_presence_of :body, :conversation_id, :user_id

    broadcasts_to :conversation
  end
end

app/models/cadmin/service.rb
module Cadmin
  class Service < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged

    include PgSearch::Model  
    include ImageUploader::Attachment(:image)
    
    belongs_to :main_service
    has_many :stock_by_dates

    validates :name, :stock, :price, presence: true


    
    def no_vat 
      (self.price / "1.#{self.vat}".to_f).round(2)
    end
  end
end

app/views/cadmin/messages/_form.html.erb
<%= form_with(model: message,data: {"controller": "quill", "action": "quill#save", turbo: false}, html: {id: 'base', class: 'article__form'}) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :body, class: 'label' %>
      <div class="control">
      <%= form.hidden_field :body, class: 'content ',data: {"quill-target": "content"} %>
        <div data-quill-target="editor" class="article__quill is-fullwidth ">
          <%= raw article.content %>
        </div> 
      </div>
    </div>
  <div class="actions my-6">
    <%= form.submit "#{t '.create'}'", class: "button is-success mx-2" %>
    <%= link_to "#{t '.cancel'}", :back, class: "button has-background-white-ter mx-2" %>
  </div>
<% end %>

app/views/cadmin/messages/_message.html.erb
<%= content_tag :div, id: dom_id(message) do %>
  <% if message.body %>
    <% user = Cadmin::User.find(message.user_id) %>
    <%if message.user_id != current_cadmin_user.id %>  
      <div class="box is-pulled-left" style="width:70%;background:rgba(255,0,0,0.2)">
      <span class="tag is-link is-pulled-right  mr-4"><%= message.created_at.strftime('%H:%M') %></span> 
    <% end %>
    <%if message.user_id == current_cadmin_user.id %>  
      <div class="box is-pulled-right" style="width:70%;background:rgba(0,255,0,0.2)">
      <span class="tag is-success is-pulled-right mr-4"><%= message.created_at.strftime('%H:%M') %></span>       
    <% end %>
      <span class="is-pulled-left">
      <%= raw message.body %> 
      </span>
      <div class="is-pulled-right mr-4">
        <span class="checkmark">
          <div class="checkmark__stem <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
          <div class="checkmark__kick <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
        </span>
        <span class="checkmark">
          <div class="checkmark__stem <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
          <div class="checkmark__kick <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
        </span>
        <%#= button_to '', @conversation.messages.find(id: message.id), method: :delete, class: 'delete is-medium',  data: { confirm: 'Are you sure?' }%>
      </div> 
    </div>
  <% end %>
<% end %>

app/views/cadmin/messages/edit.html.erb
<h1 class="title is-size-4-desktop is-size-5-touch has-text-centered"><%= t '.title' %></h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/cadmin/messages/index.html.erb
<%= turbo_frame_tag :messages do %>
  <h3 class="title is-5"><%= link_to Cadmin::User.find(@conversation.sender_id).username, "#{@conversation}/messages" %></h3>
  <% @messages.each do |message| %>
  <% if message.body %>
    <% user = Cadmin::User.find(message.user_id) %>
    <%if message.user_id != current_cadmin_user.id %>  
      <div class="box is-pulled-left" style="width:70%;background:rgba(255,0,0,0.2)">
      <span class="tag is-link is-pulled-right  mr-4"><%= message.created_at.strftime('%H:%M') %></span> 
    <% end %>
    <%if message.user_id == current_cadmin_user.id %>  
      <div class="box is-pulled-right" style="width:70%;background:rgba(0,255,0,0.2)">
      <span class="tag is-success is-pulled-right mr-4"><%= message.created_at.strftime('%H:%M') %></span>       
    <% end %>
      <span class="is-pulled-left">
      <%= raw message.body %> 
      </span>
      <div class="is-pulled-right mr-4">
        <span class="checkmark">
          <div class="checkmark__stem <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
          <div class="checkmark__kick <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
        </span>
        <span class="checkmark">
          <div class="checkmark__stem <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
          <div class="checkmark__kick <%= message.viewed ?  'checkmark__red' : ''  %>"></div>
        </span>
        <%#= button_to '', @conversation.messages.find(id: message.id), method: :delete, class: 'delete is-medium',  data: { confirm: 'Are you sure?' }%>
      </div> 
    </div>
      
      <br>
  <% end %>
  <% end %>
  <%= turbo_frame_tag :new_message,loading: :lazy,  src: new_conversation_message_path(@conversation) %>
<% end %>

app/views/cadmin/messages/new.html.erb
<h1 class="title is-size-4-desktop is-size-5-touch has-text-centered"><%= t '.title' %></h1>

<%= turbo_frame_tag :new_message do %>
  <%= form_for [@conversation, @message],data: {"controller": "quill", "action": "quill#save", turbo: false}, html: {id: 'base', class: 'article__form'} do |f| %>
    <div class="field">
      <div class="control">
      <%= f.hidden_field :body, class: 'content ',data: {"quill-target": "content"} %>
        <div data-quill-target="editor" class="is-fullwidth ">
          <%= raw @conversation.messages.last %>
        </div> 
      </div>
    </div>
    <%= f.text_field :user_id, value: current_cadmin_user.id, type: "hidden" %>
    
    <div class="actions my-6">
      <%= f.submit "#{t '.create'}'", class: "button is-success mx-2" %>
      <%= link_to "#{t '.cancel'}", :back, class: "button has-background-white-ter mx-2" %>
    </div>
  <% end %>
<% end %>

app/views/cadmin/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>