config/routes.rb
Cadmin::Engine.routes.draw do
  mount Shrine.upload_endpoint(:cache) => "/upload"
  root to: "dashboard#index"
  
  # custom routes
  get 'profile/index'
  get 'profile/edit'
  get 'profile/show'
  # get 'tags/:tag', to: 'articles#index', as: :tag
  match '/',                  to: "dashboard#index",          via: :get,      as: :dashboard
  match '/agenda',            to: "dashboard#agenda",         via: :get,      as: :agenda
  match '/interviews',        to: "interviews#index",         via: :get,      as: :interviews
  match '/interviews/:id',    to: "interviews#show",          via: :get,      as: :interview
  match '/reset-password',    to: "users#reset_password",     via: [:get,:post],      as: :reset_password
  # match '/users', to: "users#index",  via: :get, as: :users
  # match '/charged', to: "events#charged", via: :get, as: :charged
  # match '/events/:id/charged', to: "events#charged", via: :put, as: :charged
  
  # scafold resources
  resources :article_categories
  resources :discounts
  resources :event_types
  resources :locations
  resources :tags
  resources :tracks
  resources :users
  resources :web_modules
    
  resources :articles do
    resources :comments
  end
  resources :conversations do 
    resources :messages
  end

  resources :email_base_templates do
    resources :email_custom_templates, except: %w[show]
  end

  resources :events do
    resources :interviews  
  end
  
  resources :events do
    get 'booked',  on: :member
    get 'charged', on: :member 
    get 'cancel',  on: :member
  end

  resources :main_services do
    resources :services
  end

  # cart actions
  match 'cart', to: "carts#index",  via: :get, as: :cart
  resources :cart_items, only: %w[create destroy]
  get "/add/:service_id", to: "cart_items#create", as: :add_to_cart
  
  # payment routes
  # stripe webhooks
  resources :webhooks, only: %w[create]
  # stripe checkout
  get   'checkout/create',    to: 'checkout#create'
  post  'checkout/create',    to: 'checkout#create'
  get   'success',            to: 'checkout#success'
  get   'cancel',             to: 'checkout#cancel'
  
  # user authentication routes 
  # # devise_for :cadmin_users, class_name: "Cadmin::User", module: :devise
  # devise_for :users, controllers: { invitations: 'devise/invitations' }
  devise_for  :cadmin_users, 
              class_name: "Cadmin::User" , 
              controllers: { 
                sessions: 'cadmin/user_sessions', 
                registrations: 'cadmin/user_registrations',
                invitations: 'cadmin/user_invitations'
              },
              skip: [:sessions, :registrations],
              path_names: {sign_out: 'logout'},
              path_prefix: :user,
              module: :cadmin

  devise_scope :cadmin_user do
    get  'login',        to: 'user_sessions#new',              as: :login
    post 'login',        to: 'user_sessions#create',           as: :create_new_session
    get  'register',     to: 'user_registrations#new',         as: :register
    post 'register',     to: 'user_registrations#create',      as: :registration
    get  'invite',       to: 'user_invitations#new',           as: :invite
    post 'invite',       to: 'user_invitations#create',        as: :invitation
    # get  'profile',      to: 'user_registrations#edit',        as: :edit_profile
    # put  'profile',      to: 'user_registrations#update',      as: :update_profile
    get  'logout',       to: 'user_sessions#destroy',          as: :logout
  end

  # TODO: generate routes for admin and employees
  # namespace :admin do
  #   devise_for :cadmin_user,
  #               class_name: "Cadmin::User",
  #               controllers: {
  #                 sessions: 'cadmin/admin/user_sessions'
  #               },  
  #               skip: [:sessions, :registrations],
  #               path_names: { sign_out: 'logout' },
  #               path_prefix: :user
  #   devise_scope :cadmin_user do
  #     get 'login' => 'user_sessions#new', :as => :login
  #     post 'login' => 'user_sessions#create', :as => :create_new_session
  #   end
  # end

  namespace :api do 
    namespace :v1 do 
      # SPOTIFY API
      resources :tracks do 
        collection do 
          get :top_100
          get :random 
          get :search 
        end 
      end 
    end 
  end
end

app/models/cadmin/application_record.rb
module Cadmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/cadmin/article.rb
module Cadmin
  class Article < ApplicationRecord
    extend FriendlyId

    friendly_id :title, use: :slugged
    
    include PgSearch::Model  
    include ImageUploader::Attachment(:image)
    
    belongs_to :user
    belongs_to :article_category
    
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    serialize :tag_ids, Array

    delegate :username, :name, to: :user
    delegate :name, to: :article_category, prefix: :category
    
    enum status: [:pending, :published, :unpublished, :drafts ]

    validates :title, :content, presence: true

    def self.tagged_with(name)
      Tag.find_by!(name: name).articles
    end

    def self.tag_counts
      Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    end

    def tag_list 
      tags.map(&:name).join(', ')
    end

    def tag_list=(names)
      self.tags = names.split(',').map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
    end

    pg_search_scope :filter_by_search, against: [
      :title, 
      # :content, 
      # todo: complete searches
    ]
    
    def unpublish?
      self.status == 2
    end

    def draft?
      self.status == 3
    end
  end
end

app/models/cadmin/article_category.rb
module Cadmin
  class ArticleCategory < ApplicationRecord
    has_many :articles, dependent: :destroy
    validates :name, presence: true
  end
end

app/models/cadmin/cart.rb
module Cadmin
  class Cart < ApplicationRecord
    include AASM

    has_many :cart_items, dependent: :destroy
    has_many :services, through: :cart_items

    aasm.attribute_name :status

    aasm column: :status do
      state :pending, initial: true
      state :booking

      event :booked do
        transitions from: :pending, to: :booking
      end
    end

    def total_cart_amount
      self.cart_items.sum(&:service_price)
    end

    def deposit_percentage(percentage)
      self.total_cart_amount * percentage / 100
    end
  end
end

app/models/cadmin/cart_item.rb
module Cadmin
  class CartItem < ApplicationRecord
    belongs_to :service
    belongs_to :cart

    delegate :name, :price, :hour_price, :stock, :image_url, :description, :short_dscription, to: :service, prefix: 'service'

    # validates :validate_stock

    def set_cart_data (cart, service_id)
      @cart_ip = cart
      @service_id = service_id
    end

    # TODO: VALIDATION STOCK TO CALCULATE THE QUANTITY OF THE SERVICE IS AVILABLE IN THOSE DAYS
    # def validate_stock
    #   service = Service.find(@service_id)
    #   cart = Cart.find(@cart_ip).cart_items.where(service_id: @service_id)
    #   if service.stock < cart.count
    #     errors.add(:service, "No hay stock suficiente")
    #   end
    # end

  end
end

app/models/cadmin/comment.rb
module Cadmin
  class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :article
    validates :content, presence: true
  end
end

app/models/cadmin/concerns/permission_level.rb
module Cadmin
  module PermissionLevel
    extend ActiveSupport::Concern

    def user?
      %w(user employee admin superadmin).include?(self.role)
    end
    def employee?
      %w(employee admin superadmin).include?(self.role)
    end
    def admin?
      %w(admin superadmin).include?(self.role)
    end
    def superadmin?
      %w(superadmin).include?(self.role)
    end
  end
end

app/models/cadmin/conversation.rb
module Cadmin
  class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, scope: :recipient_id

    scope :between, -> (sender_id, recipient_id) do 
      where("(cadmin_conversations.sender_id = ? AND  cadmin_conversations.recipient_id =?) OR (cadmin_conversations.sender_id = ? AND cadmin_conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
    end
  end
end

app/models/cadmin/discount.rb
module Cadmin
  class Discount < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged
    validates :name, :type_discount, :percentage, :amount, presence: true
  end
end

app/models/cadmin/email_base_template.rb
module Cadmin
  class EmailBaseTemplate < ApplicationRecord
    extend FriendlyId

    friendly_id :title, use: :slugged
    
    has_many :email_custom_templates, dependent: :destroy

    validates :kind, presence: true, uniqueness: true
    validates_presence_of :title, :content

    enum kind: { 
      welcome: 0,
      reset_password: 1,
      new_event_admin: 2,
      new_event_customer: 3,
      confirmation_event: 4,
      customer_update_event: 5,
      employee_update_event: 6,
      billing_is_ready: 7,
      invitation: 8
     }

    def self.pending?
      self.kinds.keys.all? { |kind| self.pluck(:kind).include?(kind) }
    end

    def has_custom_template?
      template = self.email_custom_templates
      template.any? ? template.present? : false
    end
  
    def custom_template
      self.email_custom_templates.first
    end
  end
end

app/models/cadmin/email_custom_template.rb
module Cadmin
  class EmailCustomTemplate < ApplicationRecord
    belongs_to :email_base_template
  
    validates :content, presence: true
  
    delegate :title, :kind, to: :email_base_template, prefix: 'base'
  end
end

app/models/cadmin/event.rb
module Cadmin
  class Event < ApplicationRecord
    include PgSearch::Model
    include Cadmin::DateFormat
    include AASM
    extend FriendlyId

    friendly_id :title, use: :slugged

    belongs_to :customer,                   foreign_key: :customer_id,    class_name: 'User'
    
    belongs_to :employee,   optional: true, foreign_key: :employee_id,    class_name: 'User'
    belongs_to :place,      optional: true, foreign_key: :place_id,       class_name: 'Location'
    
    belongs_to :event_type, optional: true, foreign_key: :event_type_id,  class_name: 'EventType'
    

    has_one :interview, dependent: :destroy
    has_one :cart
    has_many :event_services, dependent: :destroy

    accepts_nested_attributes_for :event_services,
                                  allow_destroy: true,
                                  reject_if: proc { |attr| attr['service_id'].blank? }

    validates :number, presence: true, uniqueness: true  
    validates :title,:event_type, :customer, :place, :event_services, :date, presence: true
    
    # delegate data from users, places and event_types to the view
    delegate :name, :last_name, :avatar, :email, :phone, :address, :birthdate, :city, 
             :province, :postal_code, :shipping_address, :billing_address, 
             to: :customer, prefix: :customer

    delegate :name, :phone, :avatar, to: :employee, prefix: :employee

    delegate :name, to: :event_type, prefix: :type
    delegate :name, to: :place, prefix: :place

    # state machine to change status of event    
    aasm.attribute_name :status
    aasm column: :status do
      state :pending, initial: true
      state :payed, :completed, :cancelled, :booked

      event :book do 
        transitions from: :pending, to: :booked
      end

      event :pay do
        transitions from: [:pending, :booked, :completed], to: :payed
      end

      event :complete do
        transitions from: [:pending, :booked], to: :completed
      end

      event :cancel do
        transitions from: [:pending, :booked], to: :cancelled
      end
    end

    def servicenames 
      self.event_services.map(&:service_name).join(', ')
    end

    def discountnames 
      self.event_services.map(&:disocunts_name).join(',')
    end

    #! create unique number of event
    def create_number
      user = self.customer_id.to_s.rjust(5,"0") 
      number = "LGMD/#{user}-#{ Time.now.strftime('%d%m%y%H%M') }"
      self.number = number 
      self.save
    end

    #! calculate the total of the event for the associated services and discounts
    def total_services_amount
      total = 0
      self.event_services.each do |event_service|
        price = event_service.service_price if event_service.service_price.present?
        discount = event_service.discount_amount if event_service.discount_amount.present?
        discount = (price * event_service.discount_percentage) / 100  if event_service.discount_percentage.present?

        total_hours = event_service.overtime * event_service.service_hour_price

        #! save data on event_service
        event_service.total_amount = price - discount + total_hours
        event_service.save

        #! summation price, discounts and overtime
        total += event_service.total_amount
      end
      total
    end 

    def unallowed_booking? 
      available = []
      self.event_services.each {|es| available << es.in_stock? }
      available.include?(false)
    end

    
    scope :sort_by_date, -> { order('date ASC') }
    # ! SEARCH BETWEEN DATES
    scope :filter_between_dates, ->(start_date, end_date) { where(date: start_date..end_date) }
    scope :filter_by_employee_id, ->(employee_id) { where('employee_id = ?', employee_id) }
    
    # ! pgsearch busqueda por campos de texto
    # pg_search_scope :filter_by_number, against: :number
    pg_search_scope :filter_by_title, against: :title
    pg_search_scope :filter_by_status, against: :status
    
  end
end

app/models/cadmin/event_service.rb
module Cadmin
  class EventService < ApplicationRecord
    belongs_to :event
    belongs_to :service, optional: true
    belongs_to :discount, optional: true

    delegate :name, :price, :hour_price, :stock, :image_url, :description, :short_dscription, to: :service, prefix: 'service'
    delegate :name, :type_discount, :percentage, :amount, to: :discount, prefix: 'discount' 

    def in_stock?
      if StockByDate.find_by(service_id: self.id, date: self.event.date).nil?
        StockByDate.create(
          service_id: self.service_id, 
          date: self.event.date, 
          stock: self.service.stock
        )
      end
      StockByDate.find_by(service_id: self.service_id, date: self.event.date).stock_available?
    end

    def stock_decrement! 
      if StockByDate.find_by(service_id: self.service_id, date: self.event.date).stock_available? 
        sbd = StockByDate.find_by(service_id: self.service_id, date: self.event.date)
        sbd.stock -= 1
        sbd.save!
      end
    end

    def stock_increment! 
      sbd = StockByDate.find_by(service_id: self.service_id, date: self.event.date)
      sbd.stock += 1
      sbd.save!
    end
  end
end

app/models/cadmin/event_type.rb
module Cadmin
  class EventType < ApplicationRecord
    validates :name, presence: true, uniqueness: true 
    validates_presence_of :salary, :overtime_price
  end
end

app/models/cadmin/interview.rb
module Cadmin
  class Interview < ApplicationRecord
    include PgSearch::Model
    include Cadmin::DateFormat
    
    belongs_to :event
    belongs_to :employee, foreign_key: :employee_id, class_name: 'User'
    
    has_many :interview_options, dependent: :destroy    
    accepts_nested_attributes_for :interview_options, allow_destroy: true, reject_if: proc { |attr| attr['gift'].blank? }
    
    delegate :name, :phone, :avatar, to: :employee, prefix: :employee
    delegate :id, :title, :date, :customer_name, :customer_phone, :customer_email, :place_id, to: :event, prefix: :event

    scope :filter_by_pending, -> {Time.now > Event.find(self.event_id).date}
    scope :filter_by_done, -> {Time.now <= Event.find(self.event_id).date}
  end
end

app/models/cadmin/interview_option.rb
module Cadmin
  class InterviewOption < ApplicationRecord
    belongs_to :interview
  end
end

app/models/cadmin/location.rb
module Cadmin
  class Location < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged

    validates :name, presence: true
  end
end

app/models/cadmin/main_service.rb
module Cadmin
  class MainService < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged
    
    has_many :services

    validates :name, presence: true
  end
end

app/models/cadmin/message.rb
module Cadmin
  class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user
    validates_presence_of :body, :conversation_id, :user_id

    broadcasts_to :conversation
  end
end

app/models/cadmin/service.rb
module Cadmin
  class Service < ApplicationRecord
    extend FriendlyId

    friendly_id :name, use: :slugged

    include PgSearch::Model  
    include ImageUploader::Attachment(:image)
    
    belongs_to :main_service
    has_many :stock_by_dates

    validates :name, :stock, :price, presence: true


    
    def no_vat 
      (self.price / "1.#{self.vat}".to_f).round(2)
    end
  end
end

app/views/cadmin/events/_event_service_fields.html.erb
 
<div class="nested-fields">             
  <div class="field is-horizontal">
    <div class="field-body">
    
      <div class="field" style="width:25%;">
        <%= form.hidden_field :_destroy %>
        <%= form.label :service_id, class:'label required' %>
        <div class="control is-expanded" data-controller="tomselect">          
          <%= form.collection_select :service_id, Cadmin::Service.all, :id ,:name, {include_blank: true}, {class: 'form-select', data: { tomselect_target: 'tagsField' }} %>
        </div>
      </div>
      <div class="field" style="width:25%;">
        <%= form.label :discount_id, class: 'label' %>
        <div class="control is-expanded"  data-controller="tomselect">          
          <%= form.collection_select :discount_id, Cadmin::Discount.all, :id ,:name, {include_blank: true}, { class: 'form-select', data: { tomselect_target: 'tagsField' }} %>
        </div>
      </div>
      <div class="field" style="width:25%;">
        <%= form.label :overtime, class: 'label' %>
        <%= form.number_field :overtime, class: 'input' %>
      </div>
      <div class="field" style="width:25%;">
        <%= form.label :button, class: 'label has-no-opacity' %>
        <%= link_to "#{t '.remove_item'}", "#", class: 'delete is-medium is-warning',data: {action: "click->nested-form#remove_association"}%>
      </div>
      
    </div>
  </div>
</div>

app/views/cadmin/events/edit.html.erb
<h1 class="title is-size-4-desktop is-size-5-touch has-text-centered"><%= t '.title' %></h1>

<%= render 'form_edit', event: @event %>

app/views/cadmin/events/index.html.erb
<h1 class="title is-size-4-desktop is-size-5-touch has-text-centered"><%= t '.title' %></h1>
  <%= render Cadmin::SearchFormComponent.new(path: events_path,params: 'title',  button:'') if current_cadmin_user.admin? %>
<div class="is-clearfix"></div>

  <%= turbo_frame_tag :events do %>
    <div class="card has-table">
      <header class="card-header is-align-items-center pr-4">
        <div class="card-header-title"> 
          <%= link_to "#{t '.new'}", new_event_path, target: '_top',class: 'button is-primary is-outlined' if current_cadmin_user.admin? %>
          <div class="has-text-centered is-fullwidth title is-size-4-desktop is-size-5-touch">
            <%= t '.page_title' %> 
          </div>
        </div>
        <span class="tag is-info is-rounded has-tooltip-bottom mx-1" style="padding-top:5px;" data-tooltip="Eventos pendientes">
          <%= link_to inline_svg_tag('cadmin/icons/ico-information-circle.svg', class: 'icon is-small'), events_path(status: 'pending')%>
        </span>
        <span class="tag is-success is-rounded has-tooltip-bottom mx-1" style="padding-top:5px;" data-tooltip="Eventos cobrados">
         <%= link_to inline_svg_tag('cadmin/icons/ico-euro.svg', class: 'icon is-small'), events_path(status: 'payed')%>
        </span>
        <span class="tag is-danger is-rounded has-tooltip-bottom mx-1" style="padding-top:5px;" data-tooltip="Eventos Cancelados">
          <%= link_to inline_svg_tag('cadmin/icons/ico-ban.svg', class: 'icon is-small'), events_path(status: 'cancelled')%>
        </span>
        <span class="tag is-warning is-rounded has-tooltip-bottom mx-1" style="padding-top:5px;" data-tooltip="Limpipar filtros">
          <%= link_to inline_svg_tag('cadmin/icons/ico-refresh.svg', class: 'icon is-small'), events_path%>
        </span>
      </header>
      <div class="card-content">
        <div class="b-table has-pagination is-scrollable-touch">
          <div class="table-wrapper has-mobile-cards">
            <table class="table is-fullwidth is-striped is-hoverable is-fullwidth is-scrollable-touch px-4">
              <thead>
                <tr>
                  <% if 1 == 0 %>
                   <%# FIXME: pendiente de desarrollar checkbox select (all)%> 
                  <th class="is-checkbox-cell">
                    <label class="b-checkbox checkbox">
                      <input type="checkbox" value="false">
                      <span class="check"></span>
                    </label>
                  </th>
                  <% end %>
                  <th class="is-size-7-mobile"><%= link_to "#{t '.title'}", sort: 'title' %></th>
                  <th class="is-size-7-mobile"><%= link_to "#{t '.type_name'}", sort: 'type_name' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= link_to "#{t '.number'}", sort: 'number' %></th>
                  <th class="is-size-7-mobile"><%= link_to "#{t '.date'}", sort: 'date' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= link_to "#{t '.place_id'}", sort: 'place_id' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= link_to "#{t '.employee_id'}", sort: 'employee_id' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= t '.service_ids' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= t '.deposit' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= t '.pending' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= t '.total_amount' %></th>
                  <th class="is-size-7-mobile is-hidden-mobile"><%= t '.status' %></th>
                  <th class="is-size-7-mobile"><%= "#{t '.actions'}" %></th>
                </tr>
              </thead>
              <tbody>
                <% @events.each do |event| %>           
                  <tr  data-controller='charged' class="<%= "has-background-danger-light" if event.cancelled? %>  <%="has-background-success-light" if event.payed? %>">
                    <% if 1 == 0 %>
                      <%# FIXME: pendiente desarrollar checkbox select (all)%>
                      <td class="is-checkbox-cell">      
                        <%= check_box_tag :paid, event.id %>
                      </td>
                    <% end %>
                    <td class="is-size-7-mobile"><%= event.title %></td>
                    <td class="is-size-7-mobile"><%= event.type_name %></td>
                    <td class="is-size-7-mobile is-hidden-mobile"><%= event.number %></td>
                    <td data-label="date"><small class="has-text-grey is-abbr-like" title="<%= event.date %>"><%= event.date.strftime('%d-%m-%y') %></small></td>
                    <td class="is-size-7-mobile is-hidden-mobile"><%= link_to event.place_name, Cadmin::Location.find(event.place_id) %></td>
                    <td class="is-size-7-mobile is-hidden-mobile"><%= event.employee_name if event.employee_id.present? %></td>
                    <td class="is-size-7-mobile is-hidden-mobile"><%= event.servicenames  %></td>
                    <td class="is-size-7-mobile is-hidden-mobile"><%= number_with_precision(event.deposit, precision: 2) %></td>     
                    <td class="is-size-7-mobile is-hidden-mobile"><%= (event.charged || event.status == 'cancelled') ? 0 : number_with_precision(event.total_services_amount - event.deposit, precision: 2) %><%= t 'currency' %></td>               
                    <td class="is-size-7-mobile is-hidden-mobile"><%= event.status == 'cancelled' ? "0" : number_with_precision(event.total_services_amount , precision: 2) %><%= t('currency') %></td> 
                    <td data-charged-target="tag" class="is-hidden-mobile <%= event.charged == true ? 'has-background-success' : 'default'%> is-size-7-mobile"><%= t ".#{event.status}" %> </td>
                    <td class="is-actions-cell">
                      <div class="buttons is-flex-wrap-nowrap">   
                       <span class="has-tooltip-bottom mx-1"   data-tooltip="Consultar evento">                 
                        <%= link_to inline_svg_tag('cadmin/icons/ico-eye.svg', class: 'icon is-medium has-text-primary'), event ,data:{turbo_frame: "_top"}, class: 'button is-small is-clickable m-0' %>
                       </span>
                       <span class="has-tooltip-bottom mx-1"   data-tooltip="Editar evento"> 
                        <%= link_to inline_svg_tag('cadmin/icons/ico-edit.svg', class: 'icon is-medium has-text-primary'), edit_event_path(event), data:{turbo_frame: "_top"}, class: 'button is-small is-clickable m-0' %>
                       </span> 
                        <% if current_cadmin_user.admin? %>
                        <% state = event.pending? ? 'open' : 'closed'%>
                        <% color = event.pending? ? 'danger' : 'primary'%>
                        <% msg = event.pending? ? 'Confirmar evento' : 'Evento confirmado'%>
                        <span class="has-tooltip-bottom mx-1"   data-tooltip="<%= msg %>">
                         <%= link_to inline_svg_tag("cadmin/icons/ico-lock-#{state}.svg", class: "icon is-medium is-#{color} has-text-#{color}") , booked_event_path(event), data: {action: 'charged#booked',  turbo: false},  class: 'button is-small is-clickable m-0 is-hidden-mobile' %>
                        </span>
                        <span class="has-tooltip-bottom mx-1"   data-tooltip="Cancelar evento">
                        <%= link_to inline_svg_tag('cadmin/icons/ico-ban.svg', class: 'icon is-medium   has-text-primary ') , cancel_event_path(event), data: {action: 'charged#cancel',  turbo: false},  class: 'button is-small is-clickable m-0 is-hidden-mobile' %>
                        </span>
                        <span class="has-tooltip-bottom mx-1"   data-tooltip="Cobrar evento">
                          <%= link_to inline_svg_tag('cadmin/icons/ico-euro.svg', class: 'icon is-medium   has-text-primary ') , charged_event_path(event), data: {action: 'charged#change',  turbo: false},  class: 'button is-small is-clickable m-0 is-hidden-mobile' %>
                        </span>
                        <span class="has-tooltip-bottom mx-1"   data-tooltip="Eliminar evento">
                          <%= button_to event, method: :delete, data: { controller: "swal", action: "click->swal#fire", swal_options_value: default_swal_options,turbo_frame: "_top" }, class:"button is-small is-clickable m-0 is-hidden-mobile"  do %>
                            <%=  inline_svg_tag('cadmin/icons/ico-trash.svg', class: 'icon is-medium has-text-primary') %>
                          <% end %>   
                        </span>
                        <% end %>
                      </div>
                    </td>
                  </tr>
                <% end %>
                <tr>
                  <!--<td class="is-size-7-mobile is-hidden-mobile"></td>-->
                  <td class="is-size-7-mobile "><%= t '.events_count' %> </th>
                  <td class="is-size-7-mobile "><%= @events_count %></td>
                  <td class="is-hidden-mobile" colspan="1"></td>
                  <td class="is-size-7-mobile is-hidden-mobile"><%= t '.deposits' %>: </td>
                  <td class="is-size-7-mobile "><%= number_to_currency @deposits %></td>
                  <td class="is-size-7-mobile is-hidden-mobile"><%= t '.pending' %>: </td>
                  <td class="is-size-7-mobile is-hidden-mobile"><%= number_to_currency @pending_amount %></td>
                  <td class="is-hidden-mobile" colspan="3"></td>
                  <td class="is-size-7-mobile "><%= t '.total_amount' %> </td>
                  <td class="is-size-7-mobile "><%= number_to_currency @total %></td>
                  
                </tr>
              </tbody>
            </table>
            <% if @events.present? %>
              <div class="box">
                <%== pagy_bulma_nav(@pagy) %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/cadmin/events/new.html.erb
<h1 class="title is-size-4-desktop is-size-5-touch has-text-centered"><%= t '.title' %></h1>

<%= render 'form', event: @event %>